### ISSUE TITLE
Retrieve user account from disk

### ISSUE THREAD

**Issue by kernelkind** [damus-io/android#112] opened 2024-04-11 20:03 UTC
A user's account (#111) should be able to be loaded from the disk. Upon app open, this will be invoked and all accounts loaded so the column(s) can access them easily. 

Validation:
- can load a user account on Windows
- can load a user account on linux
- can load save a user account on macos
- can load a user account on android

**Comment by jb55** [comment] 2024-05-16 21:41
duplicate of:

- https://github.com/damus-io/notedeck/issues/66

**Closed by jb55** 2024-05-16 21:41 UTC
Labels: technical
