### ISSUE TITLE
Save user account to disk

### ISSUE THREAD

**Issue by kernelkind** [damus-io/android#110] opened 2024-04-11 19:53 UTC
A user's account (#111) should be able to be saved to the disk. This will be invoked after the user adds their account using #3. This issue will allow easy account retrieval on future app opens in #112.

Validation:
- can save a user account on Windows
- can save a user account on linux
- can save a user account on macos
- can save a user account on android

**Comment by jb55** [comment] 2024-05-16 21:41
Duplicate of:

- https://github.com/damus-io/notedeck/issues/66

**Closed by jb55** 2024-05-16 21:41 UTC
Labels: technical
